package obg.android.feature.analytics

object OBGAnalyticsProperties {

    const val OBG_PROP_SIGNIN_METHOD = "method"

    /**
     * Default values, always to be sent
     */
    const val OBG_PROP_SCREEN_IDENTIFIER = "screen_id"
    const val OBG_PROP_SCREEN_NAME = "screen_name" // this is the screen name, example: "splash_screen"

    // This is the subcategory for that screen, example splash: "error_loading"
    const val OBG_PROP_SCREEN_CLASS = "screen_class"
    const val OBG_PROP_SCREEN = "screen"
    const val OBG_PROP_LOCALE = "locale"
    const val OBG_PROP_CURRENCY = "currency"
    const val OBG_PROP_REVENUE = "revenue"
    const val OBG_PROP_DEVICE_TYPE = "device_type"
    const val OBG_PROP_USER_ID = "user_id"
    const val OBG_PROP_BRAND_ID = "brand_identifier"
    const val OBG_PROP_APP_PRODUCT = "app_product"
    const val OBG_PROP_VERSION_NAME = "version_name"

    /** Explore **/
    const val OBG_PROP_SORT_TYPE = "sort_type"
    const val OBG_PROP_GTM_SORT_TYPE = "gtm_sort_type"
    const val OBG_PROP_FILTER_PROVIDERS = "filter_providers" // "NetEntCasino:GameIncCasino"
    const val OBG_PROP_GTM_FILTER_PROVIDERS = "gtm_filter_providers"
    const val OBG_PROP_FILTER_ONLY_JACKPOT = "filter_only_jackpot" // Boolean

    /** Home **/
    const val OBG_PROP_ITEM_CTA = "item_cta"
    const val OBG_PROP_ITEM_CTA_TEXT = "item_cta_text"
    const val OBG_PROP_ITEM_CAPTION = "item_caption"
    const val OBG_PROP_ITEM_ID = "item_id"
    const val OBG_PROP_ITEM_SECTION_ID = "item_section_id"
    const val OBG_PROP_GTM_ITEM_SECTION_ID = "gtm_item_section_id"
    const val OBG_PROP_ITEM_SECTION_TYPE = "item_section_type"
    const val OBG_PROP_ITEM_TITLE = "item_title"
    const val OBG_PROP_GTM_ITEM_TITLE = "gtm_item_title"
    const val OBG_PROP_ITEM_TYPE = "item_type"
    const val OBG_PROP_ITEM_VIDEO_URL = "item_video_url"
    const val OBG_PROP_DEEPLINK = "deep_link_properties"
    const val OBG_PROP_GTM_DEEPLINK = "gtm_deep_link_properties"
    const val OBG_PROP_TAB_BAR_FROM = "tab_bar_item_from"
    const val OBG_PROP_TAB_BAR_TO = "tab_bar_item_to"
    const val OBG_PROP_TAB_BAR_FROM_KEY = "tab_bar_item_from_key"
    const val OBG_PROP_TAB_BAR_TO_KEY = "tab_bar_item_to_key"
    const val OBG_PROP_GTM_TAB_BAR_FROM_KEY = "gtm_tab_bar_item_from_key"
    const val OBG_PROP_GTM_TAB_BAR_TO_KEY = "gtm_tab_bar_item_to_key"
    const val OBG_PROP_NOTIFICATION_CONSENT = "consent_given"
    const val OBG_PROP_NOTIFICATION_DEEPLINK = "deeplink"

    /** Game **/
    const val OBG_PROP_BALANCE = "balance"
    const val OBG_PROP_GAME_CATEGORY = "game_category"
    const val OBG_PROP_GTM_GAME_CATEGORY = "gtm_game_category"
    const val OBG_PROP_GAME_ID = "game_id"
    const val OBG_PROP_GTM_GAME_NAME = "gtm_game_name"
    const val OBG_PROP_GAME_NAME = "game_name"
    const val OBG_PROP_GAME_PROVIDER = "game_provider"
    const val OBG_PROP_GAME_RATE_VALUE = "game_rate_value"
    const val OBG_PROP_GAME_GAMES_MODULE = "games_in_module"
    const val OBG_PROP_GAME_PAGE_NAME = "game_page_name"
    const val OBG_PROP_GAME_PAGE_ID = "game_page_id"
    const val OBG_PROP_GAME_CLICKED_NAME = "game_clicked_name"
    const val OBG_PROP_GAME_CLICKED_ID = "game_clicked_id"
    const val OBG_PROP_GAME_CLICKED_INDEX = "game_clicked_index"

    const val OBG_PROP_GAME_NAME_CAPS = "Game_Name"
    const val OBG_PROP_GAME_CATEGORY_CAPS = "Game_Category"
    const val OBG_PROP_INTERFACE_WIDGETNAME = "Interface_WidgetName"
    const val OBG_PROP_WIDGETS = "Widgets"

    /** Login **/
    const val OBG_PROP_BIOMETRICS_ENABLED = "biometrics_enabled"
    const val OBG_PROP_FIRST_LOGIN = "first_login"
    const val OBG_PROP_LOGIN_METHOD = "login_method"
    const val OBG_PROP_LOGIN_FAILURE_REASON = "failure_reason"
    const val OBG_PROP_JURISDICTION = "jurisdiction"
    const val OBG_PROP_REMEMBER_ME = "remember_me"
    const val OBG_PROP_SESSION_LIMIT_CHECK_PERIOD = "session_limit_check_period"
    const val OBG_PROP_LOGIN_TAB = "login_tab"
    const val OBG_PROP_LOGIN_FIELD_NAME_CHANGED = "login_field_name_changed"
    const val OBG_PROP_CLICKED_FROM = "clicked_from"

    const val OBG_EMAIL = "Email"
    const val OBG_PASSWORD = "Password"
    const val OBG_BIOMETRICS = "Biometrics"
    const val OBG_BANK_ID = "BankID"
    const val OBG_APP_START = "App start"
    const val OBG_MORE_MENU = "More menu"
    const val OBG_HEADER_BUTTON = "Header button"
    const val OBG_DEEPLINK = "Deeplink"
    const val OBG_GAME_PLAY = "Game Play"
    const val OBG_SESSION_TIMEOUT = "Session timeout"
    const val OBG_OTHER_LOGIN_ACTION = "Action that require login"
    const val OBG_ACCOUNT_VERIFICATION = "Account Verification"
    const val OBG_EXISTING_USER_EMAIL_LOGIN = "Existing user email login"
    const val OBG_MIT_ID = "MitID"

    /** Registration **/
    const val OBG_PROP_REGISTRATION_TYPE = "registration_type"
    const val OBG_PROP_REGISTER_ACCOUNT_CLICKED_FROM = "clicked_from"
    const val OBG_PROP_REGISTRATION_FORM_PAGE = "registration_form_page"
    const val OBG_PROP_REGISTRATION_FIELD_NAME_CHANGED = "registration_field_name_changed"
    const val OBG_PROP_REGISTRATION_BOX_CHANGED = "registration_box_changed"
    const val OBG_PROP_REGISTRATION_BOX_CHANGED_TO = "changed_to"
    const val OBG_PROP_REGISTRATION_ERROR = "error"
    const val OBG_PROP_DEEPLINK_ORIGIN = "Deeplink"

    /** More **/
    const val OBG_PROP_SELF_EXCLUSION_DURATION = "number_of_days"

    /** Payment **/
    const val OBG_PROP_PAYMENT_REFERENCE = "payment_reference"
    const val OBG_PROP_PAYMENT_METHOD = "payment_method"
    const val OBG_PROP_PAYMENT_STATUS = "payment_status"
    const val OBG_PROP_PAYMENT_TYPE = "payment_type"
    const val OBG_PROP_PAYMENT_DEPOSIT_ID = "Payment_DepositID"
    const val OBG_PROP_BONUS_TYPE_CAP = "Bonus_Type"
    const val OBG_PROP_BONUS_TITLE = "Bonus_Title"
    const val OBG_PROP_PAYMENT_CURRENCY = "Payment_Currency"
    const val OBG_PROP_PAYMENT_AMOUNT = "Payment_Amount"
    const val OBG_PROP_PAYMENT_SEL_CURRENCY = "Payment_Sel_Currency"

    /** Tournament Events **/

    const val OBG_PROP_TOURNAMENT_EVENT = "event"
    const val OBG_PROP_TOURNAMENT_EVENT_NAME = "game_tournaments_event"
    const val OBG_PROP_TOURNAMENT_EVENT_ITEM_CLICKED = "ItemClicked"
    const val OBG_PROP_TOURNAMENT_EVENT_TOURNAMENT_ID = "TournamentID"

    /** AppsFlyer properties **/
    const val OBG_PROP_APPSFLYER_DEV_KEY = "appsflyer_dev_key"
    const val OBG_PROP_APPSFLYER_ID = "appsflyer_id"
    const val OBG_PROP_APPSFLYER_AAID = "appsflyer_aaid"
    const val OBG_PROP_APPSFLYER_CUID = "appsflyer_cuid"

    /** WebView **/
    const val OBG_PROP_WEB_PAGE_NAME = "web_page_name"

    /** One Trust Consent **/
    const val OBG_PROP_CONSENT_PRIVACY_GIVEN = "consent_given"
    const val OBG_PROP_CONSENT_PRIVACY_CLICKED_FROM = "clicked_from"
    const val OBG_PROP_CONSENT_PRIVACY_DOMAIN_ID = "ot_domain_id"
    const val OBG_PROP_CONSENT_PRIVACY_STORAGE_LOCATION = "ot_storage_location"
    const val OBG_PROP_CONSENT_PRIVACY_LANGUAGE = "ot_language"
    const val OBG_PROP_CONSENT_PRIVACY_STATUS = "privacy_consent_status"

    /** Messages **/
    const val OBG_PROP_MESSAGE_ID = "message_id"
    const val OBG_PROP_CTA_TYPE = "cta_type"
    const val OBG_PROP_CTA_URL = "cta_url"
    const val OBG_PROP_TAB_CLICKED = "tab_clicked"

    /** Bonus **/
    const val OBG_PROP_BONUS_ID = "bonus_id"
    const val OBG_PROP_BONUS_STATE = "bonus_state"
    const val OBG_PROP_BONUS_TYPE = "bonus_type"
    const val OBG_PROP_BONUS_USER_ID = "user_id"
    const val OBG_PROP_BONUS_SELECTED_AMOUNT = "bonus_selected_amount"
    const val OBG_PROP_BONUS_WAGERED = "bonus_wagered"
    const val OBG_PROP_BONUS_EXPIRY_DATE = "bonus_expiry_date"
    const val OBG_PROP_NUMBER_OF_BONUSES = "number_of_bonuses"
    const val OBG_PROP_EVENT_PHASE = "Bonus_EventPhase"

    /** Onboarding **/
    const val OBG_PROP_ONBOARDING_MODULE_TYPE = "onboading_module_type"

    /** CTA to remove session limits **/
    const val SGA_PROP_CTA_REMOVE_SESSION_LIMITS = "user_id"

    /** Tournaments **/
    const val OBG_PROP_TOURNAMENT_ID = "tournament_id"

    /** Jalla **/
    const val OBG_PROP_DEPOSIT_AMOUNT = "intended_deposit_amount"
    const val OBG_PROP_DEPOSIT_PROVIDER = "deposit_provider"
    const val OBG_PROP_DEPOSIT_DAILY_LIMIT = "deposit_limit_daily_value"
    const val OBG_PROP_DEPOSIT_MONTHLY_LIMIT = "deposit_limit_monthly_value"
    const val OBG_PROP_DEPOSIT_WEEKLY_LIMIT = "deposit_limit_weekly_value"
    const val OBG_PROP_ERROR = "error"
    const val OBG_PROP_ERROR_MESSAGE = "error_message"
    const val OBG_PROP_FROM_SCREEN = "from_screen_view"
    const val OBG_PROP_ADJUSTED_DEPOSIT_AMOUNT = "adjusted_deposit_amount"
    const val OBG_PROP_IS_DEPOSIT_AMOUNT_ALLOWED = "intended_amount_allowed"
    const val OBG_PROP_DEPOSIT_PAYMENT_TYPE = "paymentType"
    const val OBG_PROP_DEPOSIT_AMOUNT_SIMPLE = "amount"
    const val OBG_PROP_DEPOSIT_IS_FIRST_DEPOSIT = "isFirstDeposit"

    /** Sportsbook **/

    // NATIVE TRACKING

    const val SB_MENU_NAME = "menu_name"
    const val SB_EVENT_SWITCHER_NAME = "event_name"
    const val SB_USER_ID = "user_id"
    const val SB_BRAND_IDENTIFIER = "brand_identifier"
    const val SB_APP_PRODUCT = "app_product"
    const val SB_SUBCAT_ID = "subCatID"
    const val SB_SUBCAT_NAME = "subCatName"
    const val SB_SEARCH_RESULT = "search_result"
    const val SB_SEARCH_EVENT_NAME = "search_event_name"
    const val SB_SEARCH_POSITION = "search_position"
    const val SB_SEARCH_TERM = "search_term"
    const val SB_MENU_CATEGORY = "menu_category"
    const val SB_RECENT_SEARCH = "Recent search"

    // IFRAME TRACKING
    const val SB_ITEM_CLICKED = "ItemClicked"
    const val SB_CATEGORY_ID = "CategoryID"
    const val SB_CATEGORY_NAME = "CategoryName"
    const val SB_EVENT_ID = "EventID"
    const val SB_EVENT_NAME = "eventName"
    const val SB_ACTION = "Action"
    const val SB_LOCATION = "Location"
    const val SB_REMEMBER_STAKE_FLAG = "RememberStakeFlag"
    const val SB_BET_TYPE = "BetType"
    const val SB_FILTER_ITEM = "FilterItem"
    const val SB_VIEW_TYPE = "ViewType"
    const val SB_FILTER_ENABLED = "FilterEnabled"
    const val SB_MARKET_TEMPLATE_ID = "MarketTemplateID"
    const val SB_SECTION_NAME = "SectionName"
    const val SB_COMPETITION_ID = "CompetitionID"
    const val SB_COMPETITION_NAME = "CompetitionName"
    const val SB_PROVIDER = "Provider"
    const val SB_EVENT_PHASE = "EventPhase"
    const val SB_TOTAL_STAKE = "TotalStake"
    const val SB_COUPON_TYPE = "CouponType"
    const val SB_TABNAME = "TabName"
    const val SB_STATUS = "Status"
    const val SB_PAGE_NAME = "page_name"
    const val SB_VIRTUAL_URL = "virtualURL"
    const val SB_VIRTUAL_TITLE = "VirtualTitle"
    const val SB_LOBBY_NAME = "LobbyName"
    const val SB_LOBBY = "Lobby"
    const val SB_GAME_LIST = "Game List"
    const val SB_EVENT = "Event"
    const val SB_SCREEN_VIEW = "screen_view"
    const val SB_APP_LOADER_LOAD_IFRAME_DURATION = "app_loader_load_iframe_duration"

    const val SB_PROP_EVENT_DETAILS = "Sportsbook_EventDetails"
    const val SB_PROP_CATEGORY_DETAILS = "Sportsbook_CategoryDetails"
    const val SB_PROP_COMPETITION_DETAILS = "Sportsbook_CompetitionDetails"
    const val SB_PROP_REMEMBER_STAKE_FLAG = "Sportsbook_RememberStakeFlag"
    const val SB_PROP_MARKET_NAME = "Sportsbook_MarketName"
    const val SB_PROP_MARKET_TEMPLATE_ID = "Sportsbook_MarketTemplateID"
    const val SB_PROP_BET_TYPE = "Sportsbook_BetType"
    const val SB_PROP_BONUS_ID = "Bonus_ID"
    const val SB_PROP_COUPON_TYPE = "Sportsbook_CouponType"

    // COMMON AREAS

    // SPORTSBOOK CUSTOM ANALYTICS PARAMETERS
    const val Native_App_Name = "Native_App_Name"
    const val Native_App_Version = "Native_App_Version"

    /** NG-6061 - New property to differentiate between tracking being
     * sent while developing/testing and actual customers. **/
    const val OBG_PROP_ACCOUNT_TYPE = "account_type"

    // CASINO FUNNEL – NG-7068
    const val OBG_PROP_CASINO_HOME_ITEM_EVENT_ACTION = "HomeItem Click"
    const val OBG_PROP_CASINO_HOME_SECTION_EVENT_ACTION = "HomeSection Click"
    const val OBG_PROP_CASINO_EVENT_ACTION = "EventAction"
    const val OBG_PROP_CASINO_SECTION_ID = "Section_Id"
    const val OBG_PROP_CASINO_ITEM_ID = "Item_Id"
    const val OBG_PROP_CASINO_ITEM_TYPE = "Item_Type"
    const val OBG_PROP_CASINO_ACTION = "Action"

    // LOGIN FUNNEL
    // Registration FUNNEL - NG-6840
    const val OBG_PROP_EVENT_ACTION = "EventAction"
    const val OBG_PROP_LOGIN_METHOD_V2 = "Login_Method"
    const val OBG_PROP_INTERFACE_COMPONENT = "Interface_Component"
    const val OBG_PROP_TECHNICAL_ERROR = "Technical_Error"
    const val OBG_PROP_GUID_EVENT = "GUID_Event"
    const val OBG_PROP_LOGIN_STATUS = "Login_Status"
    const val OBG_PROP_LOGIN__BALANCE = "Login_Balance"
    const val OBG_PROP_LOGIN_CURRENCY = "Login_Currency"
    const val OBG_PROP_USER_REG_COUNTRY = "User_Reg_Country"
    const val OBG_PROP_USER_REG_KYC_STATUS = "User_Reg_KYCStatus"
    const val OBG_PROP_TECHNICAL_START_TYPE = "Technical_StartType"
    const val OBG_CREDENTIALS = "Credentials"
    const val OBG_FACE_ID = "FaceID"
    const val OBG_LOGIN_FORM_OPEN = "Login Form Open"
    const val OBG_LOGIN_FORM_CLOSE = "Login Form Close"
    const val OBG_LOGIN_FIELD_CHANGE = "Login Field Change"
    const val OBG_LOGIN_SUBMITTED = "Login Submitted"
    const val OBG_LOGIN_FAILED = "Login Failed"
    const val OBG_LOGIN_SUCCESS_NEW = "Login Success - New"
    const val OBG_LOGIN_SUCCESS_EXISTING = "Login Success - Existing"
    const val OBG_SET_NEW_PASSWORD = "Set new Password"
    const val OBG_SKIP_PASSWORD = "Skip Password"
    const val OBG_LOGIN_INTENTION = "Login Intention"
    const val OBG_LOGIN_FORGOTTEN_PASSWORD_CLICK = "Forgotten Password Click"
    const val OBG_LOGIN_FORGOTTEN_PASSWORD_SUCCESS = "Forgotten Password Success"
    const val OBG_LOGIN_FORGOTTEN_PASSWORD_FAILED = "Forgotten Password Failed"
    const val OBG_CREATE_ACCOUNT_CLICK = "Create Account Click"
    const val OBG_LOGIN_PASSWORD_SUBMIT = "Password Form Submit"
    const val OBG_RESET_PASSWORD_FORM_OPEN = "Reset Password Form Open"
    const val OBG_RESET_PASSWORD_FORM_SUBMIT = "Reset Password Form Submit"
    const val OBG_RESET_PASSWORD_SUCCESS = "Reset Password Success"
    const val OBG_RESET_PASSWORD_FAILED = "Reset Password Failed"
    const val OBG_CHANGE_PASSWORD_FORM_OPEN = "Change Password Form Open"
    const val OBG_CHANGE_PASSWORD_FORM_SUBMIT = "ChangePasswordFormSubmit"
    const val OBG_CHANGE_PASSWORD_SUCCESS = "ChangePasswordSuccess"
    const val OBG_CHANGE_PASSWORD_FAILED = "ChangePasswordFailed"
    const val OBG_TERMS_AND_CONDITIONS_ACCEPTANCE = "Accept TC"
    const val OBG_LOGIN_TAB_CLICKS = "Login Tab Click"
    const val OBG_BANK_ID_FORM_OPEN = "BankID Form Open"
    const val OBG_OPEN_MOBILE_BANK_ID = "Open Mobile BankID"
    const val OBG_BANK_ID_START = "BankID Start"
    const val OBG_SAME_DEVICE = "Same Device"
    const val OBG_MY_ACCOUNT_CLICK = "My Account Click"
    const val OBG_PROP_INTERFACE_SECTION_NAME = "Interface_SectionName"

    // Tracking tag map
    const val OBG_PROP_USER_REGISTRATION_TYPE = "Registration_Type"
    const val OBG_PROP_USER_REG_METHOD = "User_Reg_Method"
    const val OBG_PROP_USER_REG_STEP = "User_Reg_Step"
    const val OBG_PROP_GUID_USER = "GUID_User"
    const val OBG_PROP_USER_AGE = "age"
    const val OBG_PROP_USER_SEX = "sex"
    const val OBG_PROP_USER_LOCATION = "location"
    const val OBG_PROP_USER_PARTNER_ID = "partnerID"
    const val OBG_PROP_REGISTRATION_FROM_FIELDS = "Registration Form Fields"
    const val OBG_PROP_REGISTRATION_FROM_FIELD_ERROR = "Registration Form Field Error"
    const val OBG_PROP_REGISTRATION_I_AM_NOT_SWEDISH_RESIDENT = "Registration - I am not Swedish resident"
    const val OBG_PROP_REGISTRATION_CHANGE = "Change"
    const val OBG_PROP_REGISTRATION_EVENT_ACTION = "Registration Clicks"
    const val OBG_PROP_REGISTRATION_ACTIVITY_SELECTION_EVENT_ACTION = "Activity Selection"
    const val OBG_PROP_REGISTRATION_SUBMIT_EVENT_ACTION = "Registration Submit"
    const val OBG_PROP_REGISTRATION_FAILED_EVENT_ACTION = "Registration Failed"
    const val OBG_PROP_REGISTRATION_NRC_EVENT_ACTION = "NRC"
    const val OBG_PROP_REGISTRATION_COMPLETE_VERIFIED_EVENT_ACTION = "Registration Complete Verified"
    const val OBG_PROP_REGISTRATION_COMPLETE_REGISTRATION_FROM_OPEN_EVENT_ACTION = "Registration Form Open"
    const val OBG_PROP_REGISTRATION_COMPONENT_PASSWORD = "Password"
    const val OBG_PROP_REGISTRATION_COMPONENT_EMAIL = "EMAIL"
    const val OBG_PROP_REGISTRATION_COMPONENT_PERSONAL_NUMBER = "Personal Nr"
    const val OBG_PROP_REGISTRATION_COMPONENT_PHONE = "PHONE Nr"
    const val OBG_PROP_REGISTRATION_COMPONENT_FIRST_NAME = "FirstName"
    const val OBG_PROP_REGISTRATION_COMPONENT_LAST_NAME = "FirstName"
    const val OBG_PROP_REGISTRATION_COMPONENT_DATE_OF_BIRTHDAY = "Date Of Birthday"
    const val OBG_PROP_REGISTRATION_COMPONENT_COUNTRY = "Country"
    const val OBG_PROP_REGISTRATION_COUNTRY = "Registration - Country"
    const val OBG_PROP_REGISTRATION = "Registration"
    const val OBG_PROP_REGISTRATION_COMPONENT_COUNTRY_CODE = "Country Code"
    const val OBG_PROP_REGISTRATION_COMPONENT_NATIONALITY = "Nationality"
    const val OBG_PROP_REGISTRATION_COMPONENT_BOX_AGE = "Age"
    const val OBG_PROP_REGISTRATION_COMPONENT_BOX_GENDER = "Gender"
    const val OBG_PROP_REGISTRATION_COMPONENT_NEWSLETTER_SUBSCRIPTION = "Newsletter subscription"
    const val OBG_PROP_REGISTRATION_COMPONENT_ACCEPT_TERMS_AND_CONDITION = "Accept Terms & Condition"
    const val OBG_PROP_REGISTRATION_COMPONENT_NEXT_BUTTON_STEP_1 = "Next button step1"
    const val OBG_PROP_REGISTRATION_COMPONENT_NEXT_BUTTON_STEP_2 = "Next button step2"
    const val OBG_PROP_REGISTRATION_COMPONENT_NEXT_BUTTON_STEP_3 = "Next button step3"
    const val OBG_PROP_REGISTRATION_COMPONENT_NEXT_BUTTON_STEP_5 = "Next button step5"
    const val OBG_PROP_REGISTRATION_COMPONENT_CONFIRM_BUTTON = "Confirm button"
    const val OBG_PROP_REGISTRATION_COMPONENT_CLOSE = "Close"
    const val OBG_PROP_REGISTRATION_COMPLETE_COMPONENT_BACK_BUTTON = "Back Button"
    const val OBG_PROP_REGISTRATION_COMPLETE_COMPONENT_DEPOSIT_BUTTON = "Deposit limit"
    const val OBG_PROP_REGISTRATION_COMPLETE_COMPONENT_COUNTRY = "Country"
    const val OBG_PROP_SHARE_THE_GAME_EVENT_ACTION = "Share Specific Game"
    const val OBG_PROP_GAME_GAME_ID = "Game_Id"

    // Screen View
    const val OBG_PROP_CONTENT_GROUP = "content_group"
    const val OBG_PROP_ALLOW_GOOGLE_SIGNALS = "allow_google_signals"
    const val OBG_PROP_ALLOW_AD_PERSONALIZATION_SIGNALS = "allow_ad_personalization_signals"
    const val OBG_PROP_TECHNICAL_WINDOW_TYPE = "Technical_WindowType"
    const val OBG_PROP_TECHNICAL_RAW_USER_AGENT_INFO = "Technical_RawUserAgentInfo"
    const val OBG_PROP_TECHNICAL_SCREEN_ORIENTATION = "Technical_ScreenOrientation"
    const val OBG_PROP_TECHNICAL_SCREEN_RESOLUTION = "Technical_ScreenResolution"
    const val OBG_PROP_TECHNICAL_PLATFORM_USED = "Technical_PlatformUsed"
    const val OBG_PROP_USER_CUSTOMER_LEVEL = "User_CustomerLevel"
    const val OBG_PROP_TECHNICAL_TARGETING_CONSENT = "Technical_TargetingConsent"
    const val OBG_PROP_TECHNICAL_PLATFORM_DELIVERY = "Technical_PlatformDelivery"
    const val OBG_PROP_TECHNICAL_PLATFORM_ENV = "Technical_PlatformEnv"
    const val OBG_PROP_TECHNICAL_EVENT_NAME = "Technical_EventName"
    const val OBG_PROP_TRAFFIC_TYPE = "traffic_type"
    const val OBG_PROP_USER_COUNTRY = "User_Country"
    const val OBG_PROP_INTERFACE_BRAND = "Interface_Brand"
    const val OBG_PROP_INTERFACE_SITE_LANGUAGE = "Interface_SiteLanguage"
    const val OBG_PROP_USER_UNIQUE_ID = "User_UniqueID"
    const val OBG_PROP_CUSTOMER_STATES_USER = "Customer_Status_User"
    const val OBG_PROP_CUSTOMER_STATES_EVENT = "Customer_Status_Event"
    const val OBG_PROP_NATIVE_APP_NAME = "Native_App_Name"
    const val OBG_PROP_NATIVE_APP_VERSION = "Native_App_Version"

    const val OBG_PROP_PAYMENT_SEL_AMOUNT = "Payment_Sel_Amount"
    const val OBG_PROP_INTERFACE_SEARCH_TERM = "Interface_SearchTerm"
    const val OBG_CONST_NOTIFICATION_VERIFY_ACCOUNT_OPEN = "Notification - Verify Account Open"
    const val OBG_CONST_NOTIFICATION_VERIFY_ACCOUNT_CLICK = "Notification - Verify Account Click"
    const val OBG_CONST_NOTIFICATION = "Notification"
    const val OBG_CONST_NOTIFICATION_WELCOME_MESSAGE_OPEN = "Notification - Welcome Message Open"
    const val OBG_CONST_NOTIFICATION_WELCOME_MESSAGE_OPEN_CLICKS = "Notification - Welcome Message Clicks"
    const val OBG_CONST_CONSENT_TOGGLE_FIELD_CHANGE = "Consent Toggle Field Change"
    const val OBG_CONST_CONSENT_FORM_OPEN = "Consent Form Open"
    const val OBG_CONST_GAME_CLICK = "Game Click"
    const val OBG_CONST_DEPOSIT_LIMITS_OPEN = "Deposit Limits Open"
    const val OBG_CONST_DEPOSIT_LIMITS_FAILED = "Deposit Limits Failed"
    const val OBG_CONST_DEPOSIT_LIMITS_COMPLETED = "Deposit Limits Complete"
    const val OBG_CONST_DEPOSIT_LIMITS_SUBMIT = "Deposit Limits Submit"
    const val OBG_CONST_DEPOSIT_LIMITS_CHANGE = "Deposit Limits Change"
    const val OBG_CONST_PRODUCT_FILTER_APPLIED = "Product Filter Applied"
    const val OBG_CONST_PRODUCT_FILTER_CLICKED = "Product Filter Click"
    const val OBG_CONST_PRODUCT_SORT_CLICKED = "Product Sort Click"
    const val OBG_CONST_PRODUCT_SORT_APPLIED = "Product Sort Applied"
    const val OBG_CONST_MAIN_NAVIGATION_CLICK = "Main Navigation Click"
    const val OBG_CONST_GAME_BOTTOM_NAVIGATION_CLICK = "Game Bottom Navigation Click"
    const val OBG_CONST_BALANCE_WIDGET_CLICK = "Balance Widget Click"
    const val OBG_CONST_START_PLAY_CLICK = "Start Playing Click"
    const val OBG_CONST_SGA_HEADER_LOGO_CLICK = "SGA Header Logo Click"
    const val OBG_CONST_SGA_HEADER_GAME_PAUSE = "SGA Header Game Pause"
    const val OBG_CONST_SGA_HEADER_GAME_LIMITS = "SGA Header Game Limits"
    const val OBG_CONST_SGA_HEADER_SELF_ASSESSMENT = "SGA Header Self Assessment"
    const val OBG_CONST_CONSENT_FORM_CONFIRMED = "Consent Form Confirmed"
    const val OBG_CONST_CONSENT_FORM_SUBMIT = "Consent Form Submit"
    const val OBG_CONST_BET_LIMITS_OPEN = "Bet Limits Open"
    const val OBG_CONST_BET_LIMITS_FAILED = "Bet Limits Failed"

    // payment tag map
    const val OBG_CONST_OPEN_DEPOSIT_PAGE = "Open Deposit Page"
    const val OBG_CONST_OPEN_WITHDRAWAL_PAGE = "Open Withdrawal Page"
    const val OBG_CONST_DEPOSIT_SCREEN_CLOSE = "Deposit Screen Close"
    const val OBG_CONST_WITHDRAWAL_SCREEN_CLOSE = "Withdrawal Screen Close"
    const val OBG_CONST_NEW_DEPOSIT_CUSTOMER = "NDC"
    const val OBG_CONST_RETURNING_DEPOSIT_CUSTOMER = "RDC"
    const val OBG_CONST_DEPOSIT_IN_GAME_CLICK = "Deposit in Game Click"
    const val OBG_CONST_DEPOSIT_CANCELLED = "Deposit Cancelled"
    const val OBG_CONST_SWISH_APP_START = "Swish App Start"
    const val OBG_CONST_SWISH_APP_OPEN = "Swish App Open"
    const val OBG_CONST_DEPOSIT_LIMIT_EXCEEDED = "Deposit Limit Exceeded"
    const val OBG_CONST_DEPOSIT_FIELD_CHANGE = "Deposit Field Change"
    const val OBG_CONST_DEPOSIT_DETAILS_SUBMITTED = "Deposit Details Submitted"
    const val OBG_CONST_PAYMENT_SELECTION_CHANGE = "Payment Selection Change"
    const val OBG_CONST_DEPOSIT_MAX_SUBMITTED = "Deposit Max Submitted"
    const val OBG_CONST_DEPOSIT_AMOUNT_CHANGE = "Deposit Amount Change"
    const val OBG_CONST_PAYMENT_SELECTION_OPEN = "Payment Selection Open"

    // Sportsbook

    const val OBG_CONST_PLACE_BET_CLICK = "Place Bet Click"
    const val OBG_CONST_QUICK_LINKS_SCROLLER = "Quick Links Scroller"
    const val OBG_CONST_LIVE_EVENT_VISIT = "Live Event Visit"
    const val OBG_CONST_LIVE_STREAM_INTERACTION = "Live Stream Interaction"
    const val OBG_CONST_CONTENT_LINKS_CLICK = "Content Links Click"
    const val OBG_CONST_SETTINGS_CLICK = "Settings Click"
    const val OBG_CONST_FULL_BET_HISTORY_CLICK = "Full Bet History Click"
    const val OBG_CONST_BETSLIP_DETAIL_CLICK = "Betslip Detail Click"
    const val OBG_CONST_MARKET_SELECTOR_CLICK = "Market Selector Click"
    const val OBG_CONST_MARKETSELECTORAPPLIED = "MarketSelectorApplied"
    const val OBG_CONST_BET_CONFIRMED = "Bet Confirmed"
    const val OBG_CONST_BURGER_MENU_CLICK = "Burger Menu Click"
    const val OBG_CONST_SPORTSBOOK_SEARCH = "Sportsbook Search"
    const val OBG_CONST_SPORTSBOOK_STATS_CLICK = "Sportsbook Stats Click"

    // GARBAGE DOMAIN
    const val OBG_CONST_GARBAGE_DOMAIN_URL = "garbage_domain_url"
    const val OBG_CONST_NUMBERED_DOMAIN_URL = "numbered_domain_url"
    const val OBG_CONST_SB_IFRAME_URL = "url"
    const val OBG_CONST_SB_IFRAME_COUNTRY_CODE = "country_code"

    // Casino tag map
    const val OBG_CONST_GAME_PLAYED_FOR_FUN = "Game Played For Fun"
    const val OBG_CONST_GAME_PLAYED_FOR_REAL = "Game Played For Real"
    const val OBG_CONST_GAME_FRAME_CLICK = "Game Frame Click"
    const val OBG_CONST_GAME_SEARCH = "Game Search"
    const val OBG_CONST_FAVOURITE_CLICK = "Favourite Click"
    const val OBG_CONST_MY_GAMES_CLICK = "My Games Click"
    const val OBG_CONST_VIEW_ALL_HEADER_CLICK = "View All Header Click"
    const val OBG_CONST_CASINO_FILTER_ADDED = "Casino Filter Added"
    const val OBG_CONST_CASINO_FILTER_REMOVED = "Casino Filter Removed"
    const val OBG_CONST_ADDED_IN_MY_LIST = "Added in My list"
    const val OBG_CONST_REMOVE_FROM_MY_LIST = "Remove from My list"
    const val OBG_CONST_MY_LIST_WIDGET = "My List Widget"
    const val OBG_CONST_CAROUSEL_NAVIGATION_CLICK = "Carousel Navigation Click on"

    // consent tag map
    const val OBG_CONST_MARKETING_CONSENT_ACCEPTED = "Marketing Consent Accepted"

    const val OBG_CONST_SLIDE_NUMBER = "Slide_Number"
    const val OBG_CONST_DIRECTION = "Direction"

    // DEVICE-CHECK
    const val OBG_CONST_DEVICE_CHECK_STATE = "Device State"
    const val OBG_CONST_DEVICE_CHECK_STATE_NORMAL = "Normal"
    const val OBG_CONST_DEVICE_CHECK_STATE_ROOTED = "Rooted"
    const val OBG_CONST_DEVICE_CHECK_STATE_VIRTUAL = "Virtual"
}
