package obg.android.feature.analytics

object OBGAnalyticsPage {

    const val OBG_VIEW_MYLIST = "My List"
    const val OBG_VIEW_HOME = "Home"
    const val OBG_VIEW_PRE_GAME = "Pre Game Page"
    const val OBG_VIEW_GAME_PLAY = "Game Play"
    const val OBG_VIEW_MY_ACCOUNT = "My Account"
    const val OBG_VIEW_EXPLORE = "Explore"
    const val OBG_VIEW_GAME_LIST = "Game List"
    const val OBG_VIEW_GAME_FILTER = "Game Filter"
    const val OBG_VIEW_LOGIN = "Login"
    const val OBG_VIEW_LOGIN_FORGOTPW = "Forgot Password"
    const val OBG_VIEW_SEARCH_RESULTS = "Search Results"
    const val OBG_VIEW_LIVE_CASINO = "Live Casino Lobby"
    const val OBG_VIEW_RESPONSIBLE_GAMING = "Responsible Gaming"
    const val OBG_VIEW_LICENSES = "Licenses"
    const val OBB_VIEW_PROMOTION_DETAIL = "Promotion"

    const val OBG_VIEW_MORE = "More"
    const val OBG_VIEW_PROFILE = "Profile"
    const val OBG_VIEW_CHANGE_PW = "ChangePassword"
    const val OBG_VIEW_CREATE_PASSWORD = "Create Password"
    const val OBG_CONFIRM_CHANGE_PW = "ChangePasswordConfirm"
    const val OBG_VIEW_SETTINGS = "Settings"
    const val OBG_VIEW_SETTINGS_PROMOTIONS = "Promotions"
    const val OBG_VIEW_SET_LIMIT = "Set Limit"
    const val OBG_VIEW_SELF_EXCLUSION = "Self Exclusion"
    const val OBG_VIEW_TAKE_A_BREAK = "Take a break"
    const val OBG_VIEW_SELF_ASSESSMENT = "Self Assessment"
    const val OBG_VIEW_WITHDRAW = "Payments Withdrawal"
    const val OBG_VIEW_DEPOSIT = "Payments Deposit"
    const val OBG_VIEW_BONUSES = "Bonuses"
    const val OBG_VIEW_SELECT_BONUSES = "Select Bonuses"

    const val OBG_VIEW_TOURNAMENTS = "Tournaments"
    const val OBG_VIEW_REGISTRATION_SGA = "Registration SGA"
    const val OBG_VIEW_VERIFY_REGISTRATION = "Verify BankID"
    const val OBG_VIEW_WELCOME_BACK = "Login Pop-up"
    const val OBG_VIEW_REGISTRATION_MGA1 = "Registration MGA step1"
    const val OBG_VIEW_REGISTRATION_MGA2 = "Registration MGA step2"
    const val OBG_VIEW_REGISTRATION_MGA3 = "Registration MGA step3"
    const val OBG_VIEW_REGISTRATION_MGA5 = "Registration MGA step5"
    const val OBG_VIEW_REGISTRATION_START_PAGE = "Start"
    const val OBG_VIEW_REGISTRATION_USER_DETAILS = "User Details"
    const val OBG_VIEW_REGISTRATION_DEPOSIT_LIMIT = "Deposit Limits"
    const val OBG_VIEW_REGISTRATION_BANK_ID = "BankId"

    const val OBG_VIEW_ONBOARDING_POPUP = "Onboarding Pop-up"
    const val OBG_VIEW_NON_UNIQUE_EMAIL = "Non unique email"

    const val OBG_VIEW_JALLA_SPLASH = "Splash Screen for Jalla"
    const val OBG_VIEW_PAYNPLAY_SGA_DEPOSIT = "PaynPlay SGA step 1 deposit selections"
    const val OBG_VIEW_PAYNPLAY_SGA_DEPOSIT_LIMIT = "PaynPlay SGA deposit limits"
    const val OBG_VIEW_PAYNPLAY_SGA_BANKID = "PaynPlay SGA BankId success screen"
    const val OBG_VIEW_PAYNPLAY_PERSONAL_DETAILS = "PaynPlay SGA FTU personal details"
    const val OBG_VIEW_PAYNPLAY_TERMS = "PaynPlay SGA FTU terms and condition"
    const val OBG_VIEW_PAYNPLAY_VERIFY = "PaynPlay SGA BankID verification success screen"
    const val OBG_VIEW_PAYNPLAY_BANKID_ERROR = "PaynPlay SGA BankID not installed screen"
    const val OBG_VIEW_PAYNPLAY_SGA_ERROR = "PaynPlay SGA Error screen"
    const val OBG_VIEW_PAYNPLAY_FTU_DETAILS = "PaynPlay SGA FTU personal details"
    const val OBG_VIEW_PAYNPLAY_FTU_TERMS = "PaynPlay SGA FTU terms and condition"

    // consent tag map
    const val OBG_VIEW_PRIVACY_PREFERENCE_CENTER = "Privacy Preference Center"

    /** Sportsbook **/
    const val SB_CHANGE_PASSWORD_VIEW = "change_password_view"
    const val SB_PAYMENT_WITHDRAW_VIEW = "payment_withdraw_view"
    const val SB_PAYMENT_DEPOSIT_VIEW = "payment_deposit_view"
    const val SB_LOGIN_VIEW = "login_view"
    const val SB_PAYMENTS_SV = "Payments"
    const val SB_RESPONSIBLE_GAMING = "Responsible Gaming"
    const val SB_DEPOSIT_LIMIT = "Deposit Limit"
    const val SB_SELF_ASSESMENT_RESULT = "Self Assessment Result"
    const val SB_BIOMETRIC_DIALOG = "FaceID"
    const val SB_CONTENT_PAGE = "Content Page"
    const val SB_TERMS_AND_CONDITIONS = "Terms and Conditions"
    const val SB_MY_PROFILE = "My Profile"
    const val SB_UPDATE_PROFILE = "Update Profile"
    const val SB_REGISTRATION_SV = "Registration"
    const val SB_REGISTRATION_FORM = "Registration Form"
    const val SB_REGISTRATION_SUCCESS_SC = "Registration Success"
    const val SB_SETTINGS = "Settings"
    const val MESSAGES = "Messages"
    const val SB_ACTIVE_MESSAGES = "Active"
    const val SB_EXPIRED_MESSAGES = "Expired"
    const val SB_INTEGRITY_POLICY = "Integrity Policy"
    const val SB_A_Z_MENU = "A-Z Menu"
    const val SB_SEARCH = "Search"
    const val SB_SEARCH_RESULT = "Search Result"
    const val SB_BETSLIP = "Betslip"
    const val SB_BET = "Bet"
}
