plugins {
    alias libs.plugins.android.library
    alias libs.plugins.kotlin.android
    alias libs.plugins.kotlin.kapt
    alias libs.plugins.kotlin.serialization
}

apply from: "$rootDir/config.gradle"
apply from: "$rootDir/flavorConfig.gradle"

android {
    namespace 'obg.android.feature.analytics'

    compileSdk libs.versions.build.compile.sdk.get().toInteger()

    defaultConfig {
        minSdkVersion libs.versions.build.min.sdk.get()
        targetSdkVersion libs.versions.build.target.sdk.get()

        consumerProguardFiles 'consumer-rules.pro'
    }

    buildTypes {
        dev {

        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        // Flag to enable support for the new language APIs
        coreLibraryDesugaringEnabled true
        sourceCompatibility libs.versions.java.get()
        targetCompatibility libs.versions.java.get()
    }
    kotlinOptions {
        jvmTarget = libs.versions.java.get()
    }
    buildFeatures {
        buildConfig true
    }
}

dependencies {
    coreLibraryDesugaring libs.desugar.jdk.libs

    // Only allowed project dependency is common and domain
    implementation project(':shared:common')
    implementation project(':shared:domain')

    implementation libs.kotlin.stdlib
    implementation libs.core.ktx
    testImplementation libs.junit

    implementation libs.appsflyer
    implementation libs.timber

    //Google Play
    implementation libs.play.services.ads.identifier

    //Firebase
    implementation(platform(libs.firebase.bom))
    implementation libs.firebase.perf.ktx
    implementation libs.firebase.messaging
    implementation libs.firebase.analytics

    constraints {
        implementation(libs.okhttp3) {
            because 'some firebase libraries using old version of okhttp3'
        }
    }

    testImplementation libs.junit
    testImplementation libs.mockk
    testImplementation libs.kotest.assertions.core
}
